# Generated by Django 3.2.6 on 2021-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('country', models.CharField(max_length=40)),
                ('about', models.TextField()),
            ],
        ),
    ]
