# Generated by Django 3.2.6 on 2021-09-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='grnder',
            new_name='gender',
        ),
    ]
